spring:
  application:
    name: eureka-service
  config:
    import: configserver:http://localhost:8081
  cloud:
    config:
      uri: http://localhost:8081 # Asegúrate de que esto apunte a tu config-service
server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/